# Generated by Django 3.2.10 on 2022-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restmlimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_upload', models.CharField(max_length=250, null=True)),
                ('smile_percentage', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'RestImage',
            },
        ),
        migrations.CreateModel(
            name='Restmlwebcam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_upload', models.CharField(max_length=250, null=True)),
                ('smile_percentage', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'RestWebcam',
            },
        ),
    ]
