# Generated by Django 3.2.10 on 2022-01-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restmlimage',
            name='image_upload',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='restmlwebcam',
            name='image_upload',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
