# Generated by Django 4.0 on 2022-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20220121_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restmltext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.CharField(max_length=100, null=True)),
                ('docx', models.CharField(max_length=100, null=True)),
                ('txt', models.CharField(max_length=100, null=True)),
                ('final_abstract', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'RestText',
            },
        ),
    ]
