# Generated by Django 4.0 on 2021-12-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ml_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_upload', models.CharField(max_length=250, null=True)),
                ('image_type', models.IntegerField(null=True)),
                ('smile_percentage', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'WebCam',
            },
        ),
    ]
