# Generated by Django 4.0 on 2022-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapps', '0003_blogpost_profile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default=1, max_length=130),
            preserve_default=False,
        ),
    ]
